### ISSUE TITLE
在ubuntu中找不到执行程序

### ISSUE THREAD

**Issue by miku8311** [CuteLuoBo/live-danmu-archive#2]
大佬 如题

**Comment by CuteLuoBo** [comment]
详细点，放上截图或者日志

**Comment by miku8311** [comment]
> 详细点，放上截图或日志

我会了，搞了半天原来jar包没下载。
我还有个问题，我只想要弹幕文件，我想和视频一起压制，如何把db文件中的弹幕项取出呢？或者有没办法把输出格式改为ass。

**Comment by CuteLuoBo** [comment]
> > 详细点，放上截图或日志
> 
> 我会了，搞了半天原来jar包没下载。 我还有个问题，我只想要弹幕文件，我想和视频一起压制，如何把db文件中的弹幕项取出呢？或者有没办法把输出格式改为ass。

这块在计划里，但是没搓。要展示弹幕的话得额外压制，不如直接把弹幕直接塞视频网站里面

**Comment by miku8311** [comment]
> > > 详细点，放上截图或日志
> > 
> > 
> > 我会了，原来天罐包没下载。输出把格式改为ass。
> 
> 这块在计划里，没闲置。

怎么塞？我现在使用的哔哩哔哩 自持的外挂好像只有字幕

**Comment by CuteLuoBo** [comment]
> > > > 详细点，放上截图或日志
> > > 
> > > 
> > > 我会了，原来天罐包没下载。输出把格式改为ass。
> > 
> > 
> > 这块在计划里，没闲置。
> 
> 怎么塞？我现在使用的哔哩哔哩 自持的外挂好像只有字幕

字面意思，塞弹幕

**Comment by miku8311** [comment]
> > > > > 详细点，放上截图或日志
> > > > 
> > > > 
> > > > 我会了，原来天罐包没下载。输出把格式改为ass。
> > > 
> > > 
> > > 这块在计划里，没闲置。
> > 
> > 
> > 怎么塞？我现在使用的哔哩哔哩 自持的外挂好像只有字幕
> 
> 字面意思，塞弹幕

嗷嗷，我现在可以导出danmu的数据库，在想办法怎么转换成ass。

**Comment by CuteLuoBo** [comment]
现在还没有这个功能捏

**Comment by miku8311** [comment]
> 现在还没有这个功能捏

俺想想办法 一键百度捏😎

**Comment by CuteLuoBo** [comment]
v0.3.0版本已实现弹幕转ASS文件导出功能
