### ISSUE TITLE
弹幕db文件是每次开播都单独生成一个吗

### ISSUE THREAD

**Issue by flucont** [CuteLuoBo/live-danmu-archive#3]
弹幕db文件是每次开播都单独生成一个吗。还是说一直都存到一个db里面？

**Comment by CuteLuoBo** [comment]
关于储存方式设计目前还在探索阶段，目前可以在配置文件修改，按日期划分或者直接整个合在一起。
同时按目前程序设计来看，拆分或者合并不影响具体弹幕数据的读取。后续会在数据库内增加一个主播开关播时间的记录表用于前端显示
